# buildar kogito-apps/jitexecutor
# buildar linux/macos/windows
# empacotar
# 

name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up GOLANG 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update && \
          sudo apt install -y \
          build-essential \
          maven \
          libgtk-3-dev \
          libappindicator3-dev \
          gir1.2-appindicator3-0.1 && \
          make linux

      - name: Upload Linux runner
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: runner-linux
          path: "./kogito-local-server/build/linux/runner"
