# buildar kogito-apps/jitexecutor
# buildar linux/macos/windows
# empacotar
# 

name: "CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: git submodule update && sudo apt update && sudo apt install build-essential maven -y && make
